/**
 * Saga exchange contract (SagaFactura).
 * Mirrors the JSON schema agreed with the accountant's Saga agent.
 *
 * NOTE: the TMS never generates the final invoice number. Saga assigns it
 * during validation and returns it via the /validated endpoint (sagaNumber).
 * The pending payload therefore carries only the raw invoice data + refTMS.
 */

export type SagaTip = "RON" | "VALUTA"

export interface SagaLinie {
  descriere: string // max 60
  um?: string // default "BUC"
  cantitate: number // 3 decimals
  pret: number // unit price w/o VAT, 4 decimals
  valoare: number // cantitate * pret, w/o VAT, 2 decimals
  procTVA: number // VAT percentage (RO standard rate = 21)
  tva: number // valoare * procTVA / 100, 2 decimals
}

export interface SagaFactura {
  tip: SagaTip
  clientCIF: string // customer fiscal code (CUI), digits only
  clientNume: string // max 64
  data: string // YYYY-MM-DD
  scadenta?: string // YYYY-MM-DD, default = data
  refTMS: string // TMS order reference, max 150 (NOT an invoice number)
  linii: SagaLinie[]
  moneda?: string // required when tip = VALUTA
  cursRef?: number // BNR rate, required when tip = VALUTA
}

/** Envelope returned to the agent when pulling pending invoices. */
export interface SagaPendingInvoice {
  /** TMS internal invoice id — echoed back on validation. */
  tmsInvoiceId: string
  /** TMS order reference for human context. */
  orderReference: string | null
  factura: SagaFactura
  /** Whether the agent should INSERT (new) or UPDATE (modified) the Saga doc. */
  syncAction: "insert" | "update"
  /** Existing Saga number when updating (INF_SUPLM value to locate the row). */
  sagaNumber?: string
  /**
   * Payment state recorded in TMS, sent so the agent can reflect it in Saga
   * (set NEACHITAT / record an incasare). Present when the invoice has a
   * recorded payment that needs pushing to Saga.
   */
  payment?: {
    /** Total amount paid so far (in invoice currency). */
    paidAmount: number
    /** Remaining unpaid amount. 0 = fully paid. */
    remainingAmount: number
    /** Date of the latest payment (YYYY-MM-DD), if any. */
    paidDate: string | null
    /** True when the invoice is fully paid in TMS. */
    fullyPaid: boolean
  }
}

/** Payload posted back by the agent once validated in Saga. */
export interface SagaValidatedPayload {
  tmsInvoiceId: string
  /** Final invoice number assigned in Saga (series + number). Generated by Saga. */
  sagaNumber: string
  /** Optionally the full validated SagaFactura (with any edits the accountant made). */
  factura?: SagaFactura
  /** Saga client code to remember for this customer. */
  cod?: string
  contClient?: string
  validatedAt?: string
  // --- Flat fields the agent sends for payment/totals reflection ---
  /** Total with VAT from Saga. */
  total?: number
  /** Total VAT amount. */
  tva?: number
  /** Net amount (baza TVA). */
  bazaTva?: number
  /** Unpaid remainder. 0 = fully paid. */
  neachitat?: number
  /** Internal Saga row id (for reference). */
  sagaId?: number
  /** BNR rate used for currency conversion. */
  cursRef?: number
}
