/**
 * Saga exchange contract (SagaFactura).
 * Mirrors the JSON schema agreed with the accountant's Saga agent.
 *
 * NOTE: the TMS never generates the final invoice number. Saga assigns it
 * during validation and returns it via the /validated endpoint (sagaNumber).
 * The pending payload therefore carries only the raw invoice data + refTMS.
 */

export type SagaTip = "RON" | "VALUTA"

export interface SagaLinie {
  descriere: string // max 60
  um?: string // default "BUC"
  cantitate: number // 3 decimals
  pret: number // unit price w/o VAT, 4 decimals
  valoare: number // cantitate * pret, w/o VAT, 2 decimals
  procTVA: number // VAT percentage (RO standard rate = 21)
  tva: number // valoare * procTVA / 100, 2 decimals
}

export interface SagaFactura {
  tip: SagaTip
  clientCIF: string // customer fiscal code (CUI), digits only
  clientNume: string // max 64
  data: string // YYYY-MM-DD
  scadenta?: string // YYYY-MM-DD, default = data
  refTMS: string // TMS order reference, max 150 (NOT an invoice number)
  linii: SagaLinie[]
  moneda?: string // required when tip = VALUTA
  cursRef?: number // BNR rate, required when tip = VALUTA
}

/** Envelope returned to the agent when pulling pending invoices. */
export interface SagaPendingInvoice {
  /** TMS internal invoice id — echoed back on validation. */
  tmsInvoiceId: string
  /** TMS order reference for human context. */
  orderReference: string | null
  factura: SagaFactura
}

/** Payload posted back by the agent once validated in Saga. */
export interface SagaValidatedPayload {
  tmsInvoiceId: string
  /** Final invoice number assigned in Saga (series + number). Generated by Saga. */
  sagaNumber: string
  /** Optionally the full validated SagaFactura (with any edits the accountant made). */
  factura?: SagaFactura
  /** Saga client code to remember for this customer. */
  cod?: string
  contClient?: string
  validatedAt?: string
}
