/**
 * Door/Temp Virtual-Sensor Report — PDF builder.
 *
 * Renders the same data as the print-window HTML in
 * components/telematic/door-temp-report-panel.tsx into a true PDF
 * buffer using jsPDF + jspdf-autotable. We need a real buffer (not a
 * printable HTML page) so the report can be attached to an email.
 *
 * The visual layout intentionally mirrors the HTML version:
 *   - Deep-navy brand band at the top with title, company, plate,
 *     range, generated-at timestamp, and (when present) the company
 *     logo on the right.
 *   - Column-header row in the same navy. Body rows in zebra stripes.
 *   - One-line footer "Generated by bngtracking.ro" at the bottom of
 *     each page.
 *
 * Why jsPDF and not @react-pdf or puppeteer?
 *   - jspdf + jspdf-autotable are ALREADY installed in this project.
 *   - The library runs fully in-browser, so we can build the PDF on
 *     the client, base64-encode it, and POST to /api/email/send
 *     without spinning up a headless Chromium on the server.
 */
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// Row + snapshot shapes — duplicated here (rather than imported from
// the panel component) so the PDF builder stays a leaf module without
// pulling React into any consumer that just wants to make a buffer.
export interface DoorTempRow {
  ts: Date;
  t1: number | undefined;
  t2: number | undefined;
  address: string | null;
  lat: number | null;
  lng: number | null;
}

export interface DoorTempSnapshot {
  rows: DoorTempRow[];
  sensor1Enabled: boolean;
  sensor2Enabled: boolean;
  doorSensor: boolean;
  includeLocation: boolean;
  assetPlate: string;
  companyName: string;
  /** A regular https:// URL OR a data: URL is accepted. */
  logoUrl: string;
  dateFrom: Date;
  dateTo: Date;
}

// Same operations format used everywhere else: dd.mm.yyyy - HH:MM:SS.
function fmtPdfDate(d: Date): string {
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${pad(d.getDate())}.${pad(d.getMonth() + 1)}.${d.getFullYear()} - ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
}

// Mirror of the panel's helper. Used for filename generation.
function fmtDateShort(d: Date): string {
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${pad(d.getDate())}.${pad(d.getMonth() + 1)}.${d.getFullYear()}`;
}

// Strip characters illegal in Windows / macOS file names and collapse
// whitespace into underscores. Keeps the suggested filename safe to
// drop into an email attachment slot or a downloads folder.
function sanitizeForFilename(s: string): string {
  return s
    .replace(/[\\/:*?"<>|]+/g, "")
    .replace(/\s+/g, "_")
    .replace(/_+/g, "_")
    .trim();
}

// Door-state model copied verbatim from the panel: transitions are
// row indices where state flips, starting Closed.
function computeDoorState(rowIndex: number, transitions: number[]): "Open" | "Closed" {
  let flips = 0;
  for (const t of transitions) {
    if (t <= rowIndex) flips++;
    else break;
  }
  return flips % 2 === 1 ? "Open" : "Closed";
}

/**
 * Fetch an image URL and return it as a base64 data URL so jsPDF can
 * embed it. Returns null on any failure (cors, 404, etc.) — the PDF
 * then renders without the logo, identical to how the HTML print
 * window degrades when the logo URL is unreachable.
 */
async function loadImageAsDataUrl(url: string): Promise<{ dataUrl: string; format: "PNG" | "JPEG" } | null> {
  try {
    const res = await fetch(url, { mode: "cors" });
    if (!res.ok) return null;
    const blob = await res.blob();
    const dataUrl: string = await new Promise((resolve, reject) => {
      const r = new FileReader();
      r.onload = () => resolve(r.result as string);
      r.onerror = reject;
      r.readAsDataURL(blob);
    });
    // jsPDF needs the FORMAT argument to match the image bytes. We
    // peek at the data-url prefix instead of trusting the extension
    // in the URL (some CDNs serve PNGs from .jpg URLs).
    const format: "PNG" | "JPEG" = dataUrl.startsWith("data:image/png") ? "PNG" : "JPEG";
    return { dataUrl, format };
  } catch {
    return null;
  }
}

export interface BuildDoorTempPdfResult {
  /** Raw bytes — useful when caller wants to upload to blob storage. */
  buffer: Uint8Array;
  /** Same bytes base64-encoded — what /api/email/send expects. */
  base64: string;
  /** Suggested file name with no extension prefixes stripped. */
  filename: string;
}

/**
 * Build the PDF entirely on the client and return both raw bytes and
 * a base64 string. The base64 form is what the email-send endpoint
 * needs as `attachments[].content`.
 */
export async function buildDoorTempPdf(
  snap: DoorTempSnapshot,
  transitions: number[],
): Promise<BuildDoorTempPdfResult> {
  // ── Filename (used in title + as attachment name) ──
  const sensorsLabel = [
    snap.sensor1Enabled ? "SensorTemp1" : null,
    snap.sensor2Enabled ? "SensorTemp2" : null,
  ].filter(Boolean).join("+") || "NoSensors";
  const plateSlug = sanitizeForFilename(snap.assetPlate || "Vehicle");
  const rangeSlug = `${fmtDateShort(snap.dateFrom)}-${fmtDateShort(snap.dateTo)}`;
  const filename = `${plateSlug}_${rangeSlug}_${sensorsLabel}`;

  // ── Document ──
  const doc = new jsPDF({ unit: "pt", format: "a4", orientation: "portrait" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Brand colour parsed once. Same hex as the print window.
  const BRAND_BLUE: [number, number, number] = [17, 18, 34]; // #111222

  // ── Header band (drawn on EVERY page via didDrawPage hook) ──
  // We pre-load the logo so the async cost is paid up-front; the
  // didDrawPage callback itself stays sync.
  const logo = snap.logoUrl ? await loadImageAsDataUrl(snap.logoUrl) : null;

  const headerHeight = 90;
  const generatedAt = fmtPdfDate(new Date());
  const rangeLabel = `${fmtPdfDate(snap.dateFrom)}  ->  ${fmtPdfDate(snap.dateTo)}`;

  const drawHeader = () => {
    doc.setFillColor(...BRAND_BLUE);
    doc.rect(0, 0, pageWidth, headerHeight, "F");

    // Title
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("Temperature Report", 32, 30);

    // Meta lines
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    let y = 48;
    if (snap.companyName) {
      doc.setFont("helvetica", "bold");
      doc.text(snap.companyName, 32, y);
      doc.setFont("helvetica", "normal");
      y += 12;
    }
    doc.text(snap.assetPlate, 32, y); y += 12;
    doc.text(`Range:  ${rangeLabel}`, 32, y); y += 12;
    doc.text(`Generated:  ${generatedAt}`, 32, y);

    // Logo on the right — clamped to a 130x60 box, kept inside a
    // white badge so a coloured logo still reads on the dark band.
    if (logo) {
      const boxW = 130;
      const boxH = 60;
      const boxX = pageWidth - boxW - 24;
      const boxY = (headerHeight - boxH) / 2;
      doc.setFillColor(255, 255, 255);
      doc.roundedRect(boxX, boxY, boxW, boxH, 4, 4, "F");
      try {
        doc.addImage(logo.dataUrl, logo.format, boxX + 6, boxY + 4, boxW - 12, boxH - 8, undefined, "FAST");
      } catch {
        // addImage can throw on malformed data — fall through silently.
      }
    }
  };

  // ── Table header / body ──
  const head: string[] = ["Timestamp"];
  if (snap.includeLocation) head.push("Location");
  if (snap.doorSensor) head.push("Door");
  if (snap.sensor1Enabled) head.push("SensorTemp1");
  if (snap.sensor2Enabled) head.push("SensorTemp2");

  const body = snap.rows.map((r, i) => {
    const cells: string[] = [fmtPdfDate(r.ts)];
    if (snap.includeLocation) {
      cells.push(
        r.address ??
        (r.lat != null && r.lng != null ? `${r.lat.toFixed(5)}, ${r.lng.toFixed(5)}` : "—"),
      );
    }
    if (snap.doorSensor) cells.push(computeDoorState(i, transitions));
    if (snap.sensor1Enabled) cells.push(r.t1 != null ? r.t1.toFixed(1) : "—");
    if (snap.sensor2Enabled) cells.push(r.t2 != null ? r.t2.toFixed(1) : "—");
    return cells;
  });

  // Column alignment per column index. Match the HTML layout.
  const columnStyles: Record<number, { halign?: "left" | "center" | "right" }> = {};
  let colIdx = 1;
  if (snap.includeLocation) { columnStyles[colIdx] = { halign: "left" }; colIdx++; }
  if (snap.doorSensor) { columnStyles[colIdx] = { halign: "center" }; colIdx++; }
  if (snap.sensor1Enabled) { columnStyles[colIdx] = { halign: "right" }; colIdx++; }
  if (snap.sensor2Enabled) { columnStyles[colIdx] = { halign: "right" }; colIdx++; }

  autoTable(doc, {
    head: [head],
    body,
    startY: headerHeight + 16,
    margin: { top: headerHeight + 12, left: 24, right: 24, bottom: 32 },
    styles: {
      font: "helvetica",
      fontSize: 9,
      cellPadding: { top: 4, right: 6, bottom: 4, left: 6 },
      lineColor: [236, 236, 236],
      lineWidth: 0.5,
      textColor: [26, 26, 26],
      overflow: "linebreak",
    },
    headStyles: {
      fillColor: BRAND_BLUE,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      halign: "left",
    },
    alternateRowStyles: { fillColor: [247, 248, 250] },
    columnStyles: {
      0: { halign: "left" },
      ...columnStyles,
    },
    // Colour the Door cell text — green for Closed, red for Open —
    // to match the HTML preview. The didParseCell hook fires per
    // cell before drawing, so colour mutations stick.
    didParseCell: (data) => {
      if (data.section !== "body") return;
      // Find the door column index inside this render (depends on which
      // optional columns are present).
      let doorColIdx = -1;
      let idx = 1;
      if (snap.includeLocation) idx++;
      if (snap.doorSensor) doorColIdx = idx;
      if (doorColIdx === -1 || data.column.index !== doorColIdx) return;
      const v = data.cell.text?.[0];
      if (v === "Open") data.cell.styles.textColor = [185, 28, 28];
      else if (v === "Closed") data.cell.styles.textColor = [21, 128, 61];
      data.cell.styles.fontStyle = "bold";
    },
    didDrawPage: () => {
      drawHeader();
      // Page footer — small grey strip.
      doc.setFontSize(8);
      doc.setTextColor(107, 114, 128);
      const footer = "Generated by bngtracking.ro";
      const w = doc.getTextWidth(footer);
      doc.text(footer, (pageWidth - w) / 2, pageHeight - 14);
    },
  });

  // ── Set the document title so any reader's tab-strip shows it ──
  doc.setProperties({
    title: filename,
    subject: "Temperature Report",
    creator: "BNG Tracking",
  });

  // jsPDF returns an ArrayBuffer with output('arraybuffer'). Wrap to
  // Uint8Array and produce the base64 form needed by /api/email/send.
  const arr = doc.output("arraybuffer") as ArrayBuffer;
  const buffer = new Uint8Array(arr);
  // btoa requires a binary string. Chunk to avoid the call-stack
  // overflow that happens on multi-MB PDFs.
  let binary = "";
  const CHUNK = 0x8000;
  for (let i = 0; i < buffer.length; i += CHUNK) {
    binary += String.fromCharCode.apply(null, Array.from(buffer.subarray(i, i + CHUNK)));
  }
  const base64 = typeof window !== "undefined" ? window.btoa(binary) : Buffer.from(buffer).toString("base64");

  return { buffer, base64, filename };
}
