/**
 * POST /api/saga/invoices/validated
 *
 * Called by the Saga agent after the accountant validates an invoice in Saga,
 * or when payment/totals change in Saga and need to be reflected in TMS.
 *
 * Writes the final Saga invoice number back onto the TMS invoice, applies any
 * edits the accountant made, maps payment state from `neachitat`, and remembers
 * the customer's Saga client code.
 *
 * Auth: x-api-key / x-api-username / x-api-secret  (scope: saga:write)
 *
 * Body: SagaValidatedPayload
 *   {
 *     tmsInvoiceId: string,
 *     sagaNumber: string,
 *     cod?: string,
 *     contClient?: string,
 *     factura?: SagaFactura,
 *     validatedAt?: string,
 *     // Flat fields for payment/totals:
 *     total?: number,      // total with VAT
 *     tva?: number,        // VAT amount
 *     bazaTva?: number,    // net amount
 *     neachitat?: number,  // unpaid remainder (0 = fully paid)
 *     sagaId?: number,     // Saga row id
 *     cursRef?: number     // BNR rate
 *   }
 */

import { type NextRequest, NextResponse } from "next/server"
import { authenticateApiRequest, getServiceClient } from "@/lib/api-auth"
import type { SagaValidatedPayload } from "@/lib/saga/types"

export const runtime = "nodejs"
export const dynamic = "force-dynamic"

export async function POST(req: NextRequest) {
  const auth = await authenticateApiRequest(req, "saga:write")
  if (!auth.ok || !auth.credential) {
    return NextResponse.json({ error: auth.error }, { status: auth.status })
  }
  const adminId = auth.credential.admin_id

  let body: SagaValidatedPayload
  try {
    body = (await req.json()) as SagaValidatedPayload
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 })
  }

  if (!body?.tmsInvoiceId || !body?.sagaNumber) {
    return NextResponse.json({ error: "tmsInvoiceId and sagaNumber are required" }, { status: 400 })
  }

  // Invoices created directly in Saga (not originating from TMS) have no TMS
  // reference, so the agent sends a synthetic id like "saga-1666". These are not
  // TMS invoices — acknowledge and ignore them instead of failing the UUID lookup.
  const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
  if (!UUID_RE.test(body.tmsInvoiceId)) {
    return NextResponse.json({
      ok: true,
      ignored: true,
      reason: "tmsInvoiceId is not a TMS invoice (Saga-only document)",
      tmsInvoiceId: body.tmsInvoiceId,
      sagaNumber: body.sagaNumber,
    })
  }

  const supabase = getServiceClient()

  // Ensure the invoice belongs to this tenant and is queued for Saga.
  const { data: invoice, error: fetchErr } = await supabase
    .from("order_invoices")
    .select("id, business_partner_id, accounting_system, total_with_tax, amount")
    .eq("id", body.tmsInvoiceId)
    .eq("admin_id", adminId)
    .maybeSingle()

  if (fetchErr) {
    return NextResponse.json({ error: fetchErr.message }, { status: 500 })
  }
  if (!invoice) {
    return NextResponse.json({ error: "Invoice not found" }, { status: 404 })
  }

  // Recompute totals from the validated factura if provided, OR from flat fields.
  // Priority: factura.linii > flat total/bazaTva/tva > keep existing.
  const update: Record<string, any> = {
    accounting_system: "saga",
    accounting_sync_id: body.sagaNumber,
    accounting_sync_at: body.validatedAt || new Date().toISOString(),
    accounting_sync_error: null,
    // The invoice number is generated by Saga at validation — store it as the
    // official number on the TMS invoice.
    invoice_number: body.sagaNumber,
    external_invoice_number: body.sagaNumber,
    updated_at: new Date().toISOString(),
  }

  // Default sync status to 'synced' (we'll override to 'paid' below if applicable)
  let nextSyncStatus = "synced"

  // Determine totals: prefer factura.linii, else use flat fields, else keep existing
  let totalWithTax: number | null = null
  let netAmount: number | null = null

  if (body.factura?.linii?.length) {
    const valoare = body.factura.linii.reduce((s, l) => s + (Number(l.valoare) || 0), 0)
    const tva = body.factura.linii.reduce((s, l) => s + (Number(l.tva) || 0), 0)
    netAmount = Math.round((valoare + Number.EPSILON) * 100) / 100
    totalWithTax = Math.round((valoare + tva + Number.EPSILON) * 100) / 100
    update.amount = netAmount
    update.total_with_tax = totalWithTax
    update.line_items = body.factura.linii
    if (body.factura.data) update.issue_date = body.factura.data
    if (body.factura.scadenta) update.due_date = body.factura.scadenta
  } else if (body.total != null || body.bazaTva != null) {
    // Use flat fields from agent
    if (body.bazaTva != null) {
      netAmount = Math.round((body.bazaTva + Number.EPSILON) * 100) / 100
      update.amount = netAmount
    }
    if (body.total != null) {
      totalWithTax = Math.round((body.total + Number.EPSILON) * 100) / 100
      update.total_with_tax = totalWithTax
    }
  }

  // Map payment state from neachitat (unpaid remainder)
  // neachitat = 0 → fully paid
  // 0 < neachitat < total → partially paid
  // neachitat >= total or null → unpaid (status=issued)
  const existingTotal = totalWithTax ?? invoice.total_with_tax ?? invoice.amount
  if (body.neachitat != null && existingTotal != null && existingTotal > 0) {
    const neachitat = Math.round((body.neachitat + Number.EPSILON) * 100) / 100
    const total = Math.round((existingTotal + Number.EPSILON) * 100) / 100

    if (neachitat <= 0) {
      // Fully paid — lock the invoice
      update.status = "paid"
      update.paid_amount = total
      update.remaining_amount = 0
      update.paid_date = new Date().toISOString().split("T")[0]
      nextSyncStatus = "paid" // locked from further re-sync
    } else if (neachitat < total) {
      // Partially paid
      update.status = "partially_paid"
      update.paid_amount = Math.round((total - neachitat + Number.EPSILON) * 100) / 100
      update.remaining_amount = neachitat
    } else {
      // Unpaid (neachitat >= total)
      update.status = "issued"
      update.paid_amount = 0
      update.remaining_amount = total
    }
  } else {
    // No neachitat provided — just mark as issued
    update.status = "issued"
  }

  update.accounting_sync_status = nextSyncStatus

  const { error: updateErr } = await supabase
    .from("order_invoices")
    .update(update)
    .eq("id", body.tmsInvoiceId)
    .eq("admin_id", adminId)

  if (updateErr) {
    await supabase.from("saga_sync_log").insert({
      admin_id: adminId,
      order_invoice_id: body.tmsInvoiceId,
      api_credential_id: auth.credential.id,
      direction: "validate",
      status: "error",
      error: updateErr.message,
      payload: body as any,
    })
    return NextResponse.json({ error: updateErr.message }, { status: 500 })
  }

  // Remember the customer's Saga client code for future invoices.
  if (invoice.business_partner_id && (body.cod || body.contClient)) {
    await supabase
      .from("saga_partner_mappings")
      .upsert(
        {
          admin_id: adminId,
          business_partner_id: invoice.business_partner_id,
          saga_cod: body.cod ?? null,
          cont_client: body.contClient ?? null,
          updated_at: new Date().toISOString(),
        },
        { onConflict: "admin_id,business_partner_id" },
      )
  }

  await supabase.from("saga_sync_log").insert({
    admin_id: adminId,
    order_invoice_id: body.tmsInvoiceId,
    api_credential_id: auth.credential.id,
    direction: "validate",
    status: "ok",
    payload: body as any,
  })

  return NextResponse.json({ ok: true, tmsInvoiceId: body.tmsInvoiceId, sagaNumber: body.sagaNumber })
}
